# Generated by Django 3.2.3 on 2021-05-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kinomaniak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='filmy',
            name='gatunek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kinomaniak.gatunki'),
        ),
    ]
